services:
  - type: web
    name: anaesthetik-ghost
    env: node
    plan: free
    buildCommand: |
      npm install
    startCommand: |
      npm start --development
    envVars:
      - key: NODE_ENV
        value: development
      - key: url
        value: https://anaesthetik.onrender.com
      - key: database__client
        value: sqlite3
      - key: database__connection__filename
        value: content/data/ghost.db
      - key: mail__transport
        value: direct
    autoDeploy: true
